### ISSUE TITLE
check_errors submission can be None

### ISSUE THREAD

**Issue by pmdevita** [pmdevita/switcharoohelper#35]
Not sure how this happens but apparently it does
```
Traceback (most recent call last):
  File "/home/switcharoo/switcharoo/check_up.py", line 101, in <module>
    reprocess(reddit, roo, last_switcharoo, action, stage=consts.ONLY_BAD, mute=args.unmute_delete)
  File "/home/switcharoo/switcharoo/core/process.py", line 60, in reprocess
    new_tracker = check_errors(reddit, last_switcharoo, roo, submission=roo.submission)
  File "/home/switcharoo/switcharoo/core/process.py", line 256, in check_errors
    if submission.domain[-10:] != "reddit.com":
TypeError: 'NoneType' object is not subscriptable
```

Write a test for it too

**Comment by pmdevita** [comment]
This happened due to I think some kind of issue with crossposting, not entirely sure. It was fixed in the middle of the January 2023 sprint but I don't remember at all what the problem was. It might be covered by the tests though.
